<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="8867005c072f" name="cz.koncentrator_v2.api.cert.common.test.CERTFactoryTest" tests="3" failures="2" timestamp="9 Oct 2016 23:59:02 GMT" time="0.680" errors="0">
  <testcase name="test2" time="0.165" classname="cz.koncentrator_v2.api.cert.common.test.CERTFactoryTest">
    <failure type="java.lang.ClassCastException" message="Cannot cast java.lang.Class to cz.koncentrator_v2.api.cert.CreateCa.CreateCaInterface">
      <![CDATA[java.lang.ClassCastException: Cannot cast java.lang.Class to cz.koncentrator_v2.api.cert.CreateCa.CreateCaInterface
	at java.lang.Class.cast(Class.java:3369)
	at cz.koncentrator_v2.api.cert.common.CERTFactory.findClassForInterface(CERTFactory.java:58)
	at cz.koncentrator_v2.api.cert.common.CERTFactory.getInstanceForCreateCa(CERTFactory.java:127)
	at cz.koncentrator_v2.api.cert.common.test.CERTFactoryTest.test2(CERTFactoryTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.121" classname="cz.koncentrator_v2.api.cert.common.test.CERTFactoryTest">
    <failure type="java.lang.ClassCastException" message="Cannot cast java.lang.Class to cz.koncentrator_v2.api.cert.GenerateServer.GenerateServerInterface">
      <![CDATA[java.lang.ClassCastException: Cannot cast java.lang.Class to cz.koncentrator_v2.api.cert.GenerateServer.GenerateServerInterface
	at java.lang.Class.cast(Class.java:3369)
	at cz.koncentrator_v2.api.cert.common.CERTFactory.findClassForInterface(CERTFactory.java:58)
	at cz.koncentrator_v2.api.cert.common.CERTFactory.getInstanceForGenerateServer(CERTFactory.java:135)
	at cz.koncentrator_v2.api.cert.common.test.CERTFactoryTest.test3(CERTFactoryTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test" time="0.394" classname="cz.koncentrator_v2.api.cert.common.test.CERTFactoryTest"/>
</testsuite> <!-- cz.koncentrator_v2.api.cert.common.test.CERTFactoryTest -->
